name: Common CI Action

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]
  schedule:
    - cron: '58 * * * *'

jobs:
  job1:
    environment: dev
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          logout: false

      - name: Info
        run: |
          COUNT=$(docker run ${{ secrets.DOCKER_IMAGE }} | jq '.count')
          echo "count=$COUNT"
          if [ "$COUNT" -eq 1 ]; then
            curl -X POST \
              -H "Content-Type: ${{ secrets.CONTENT_TYPE }}" \
              -H "Authorization: ${{ secrets.DAILY_REPORT_AUTH }}" \
              -d '${{ secrets.CONTENT_BODY }}' \
              ${{ secrets.ENDPOINT }}
          else
            # send error mail to common
            echo "err err1"
          fi
