name: Simple Workflow

on:
  push:
    branches: [ main ]

jobs:
  job1:
    environment: dev
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_NAME }} --password-stdin

      - name: Info
        run: |
          RES="$(docker run ${{ secrets.DOCKER_IMAGE }})"
          echo $RES
          echo $RES | jq

      - name: Logout
        run: docker logout


  # build:
  #   # if: github.ref_name != 'whoohoo'
  #   environment: dev
  #   needs: job1
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10

  #   steps:
  #     - name: Send HTTP Get
  #       run: |
  #         response=$(curl -s -m 10 https://ipinfo.io/ip)
  #         echo "$response"
  #     - name: Run a simple command
  #       run: |
  #         node --version
  #         echo ${{ secrets.IMAGE_USE }}
