name: Simple Workflow

on:
  push:
    branches: [ main ]

jobs:
  job1:
    environment: dev
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_NAME }} --password-stdin

      - name: Info
        run: docker run --rm ${{ secrets.DOCKER_IMAGE }} node --version

      - name: Logout
        run: docker logout

      - name: Send HTTP Get
        run: |
          response=$(curl -s -m 10 https://ipinfo.io/ip)
          echo "$response"

  build:
    # if: github.ref_name != 'whoohoo'
    environment: dev
    needs: job1
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Run a simple command
        run: |
          node --version
          echo ${{ secrets.IMAGE_USE }}
